## 00. PyTorch Fundamentals 

In [1]:
!nvidia-smi

Wed Aug  6 23:34:42 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.64.03              Driver Version: 575.64.03      CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   37C    P0             12W /   55W |      11MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
 

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 1.13.1+cu117
CUDA available: True


## Introduction to tensors 

### Creating tensors 

PyTorch tensors are created by using torch.Tensor()

In [ ]:
# Scalar (escalar de toda la vida)
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim # Number of dimensions

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector 
vector = torch.tensor([7, 7])
vector 

tensor([7, 7])

In [8]:
vector.ndim # (lo mismo)

1

In [ ]:
vector.shape # (Numero de elementos)

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX 

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim # (Dimensiones = nº de "caminos" por los que se puede ir) 

2

In [ ]:
MATRIX.shape # (Dos elementos donde cada uno contiene dos sub-elementos)

torch.Size([2, 2])

In [27]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,7],
                        [4,5,6,7],
                        [7,8,9,7]],
                       
                       [[10,11,12,7],
                        [13,14,15,7],
                        [16,17,18,7]]])
TENSOR

tensor([[[ 1,  2,  3,  7],
         [ 4,  5,  6,  7],
         [ 7,  8,  9,  7]],

        [[10, 11, 12,  7],
         [13, 14, 15,  7],
         [16, 17, 18,  7]]])

In [18]:
TENSOR.ndim 

3

In [28]:
TENSOR.shape

torch.Size([2, 3, 4])

### Random tensors 

Why random tensors? 

NN start with random weights (random tensors) -> look at data -> update -> look data -> (...)

In [33]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.1300, 0.5308, 0.7321, 0.8907],
         [0.9532, 0.0459, 0.7172, 0.6025],
         [0.5383, 0.3021, 0.9949, 0.2213]]])

In [34]:
random_tensor.ndim # (Matriz)

3

In [35]:
random_tensor.shape # (3 filas, 4 columnas)

torch.Size([1, 3, 4])

In [67]:
# Create random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [65]:
random_image_size_tensor

tensor([[[0.6773, 0.7798, 0.3014],
         [0.9306, 0.4457, 0.9930],
         [0.3591, 0.1039, 0.3479],
         ...,
         [0.3302, 0.7986, 0.1575],
         [0.2738, 0.2651, 0.5488],
         [0.4712, 0.3486, 0.3403]],

        [[0.8406, 0.9530, 0.6105],
         [0.8196, 0.8694, 0.8267],
         [0.5006, 0.4090, 0.5743],
         ...,
         [0.2525, 0.3016, 0.2637],
         [0.5097, 0.9456, 0.8121],
         [0.7306, 0.4887, 0.0401]],

        [[0.1503, 0.5969, 0.0311],
         [0.7533, 0.5592, 0.7001],
         [0.2912, 0.8265, 0.8492],
         ...,
         [0.8438, 0.5840, 0.8278],
         [0.7325, 0.5772, 0.5032],
         [0.5622, 0.1171, 0.6884]],

        ...,

        [[0.5151, 0.9986, 0.3422],
         [0.7160, 0.6803, 0.9872],
         [0.6389, 0.1992, 0.7569],
         ...,
         [0.4955, 0.7606, 0.2852],
         [0.0635, 0.4530, 0.6371],
         [0.5599, 0.4273, 0.7393]],

        [[0.0557, 0.3352, 0.7123],
         [0.2069, 0.3122, 0.5264],
         [0.

In [69]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
zeros * random_tensor # Element-wise multiplication

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [72]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [74]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [77]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
# Tensors like 
ten_zeros = torch.zeros_like(input=one_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**NOTE**: Tensor datatypes are one of the big three issues with PyTorch & Deep learning:
    1. Tensors not right datatype
    2. Tensors not right shape 
    3. Tensors not right device 

In [83]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What data type is the tensor (float32, float16,...)
                               device=None, # What device is the tensor on (CPU, GPU)
                               requires_grad=False) # Whetther or not to track gradients with this tensor

float_32_tensor.dtype

torch.float32

In [85]:
float_16_tensor = float_32_tensor.type(torch.float16) # Changes tensor datatype to another 

In [ ]:
float_16_tensor * float_32_tensor # Works, but not all operations works

tensor([ 9., 36., 81.])

In [91]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [93]:
int_32_tensor * float_32_tensor # Works, but not all operations works

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype -> 'tensor.dtype'
2. Tensors not right shape -> 'tensor.shape'
3. Tensors not right device -> 'tensor.device'

In [105]:
# Create tensor 
some_tensor = torch.rand(size=(3, 4))
some_tensor

tensor([[0.7738, 0.2910, 0.7728, 0.7018],
        [0.7431, 0.4751, 0.6288, 0.8668],
        [0.0185, 0.2362, 0.4701, 0.5334]])

In [ ]:
print(f"Some tensor: \n{some_tensor}")
print(f"- Datatype of tensor: {some_tensor.dtype}")
print(f"- Shape of tensor: {some_tensor.shape}")
print(f"- Device tensor is on: {some_tensor.device}")

Some tensor: 
tensor([[0.7738, 0.2910, 0.7728, 0.7018],
        [0.7431, 0.4751, 0.6288, 0.8668],
        [0.0185, 0.2362, 0.4701, 0.5334]])
- Datatype of tensor: torch.float32
- Shape of tensor: torch.Size([3, 4])
- Device tensor is on: cpu
