## 00. PyTorch Fundamentals 

In [1]:
!nvidia-smi

Sat Aug  9 18:04:00 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 575.64.03              Driver Version: 575.64.03      CUDA Version: 12.9     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4060 ...    Off |   00000000:01:00.0 Off |                  N/A |
| N/A   35C    P0             12W /   55W |      11MiB /   8188MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [2]:
import torch
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
 

print("PyTorch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

PyTorch version: 1.13.1+cu117
CUDA available: True


## Introduction to tensors 

### Creating tensors 

PyTorch tensors are created by using torch.Tensor()

In [3]:
# Scalar (escalar de toda la vida)
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim # Number of dimensions

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector 
vector = torch.tensor([7, 7])
vector 

tensor([7, 7])

In [7]:
vector.ndim # (lo mismo)

1

In [8]:
vector.shape # (Numero de elementos)

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8], 
                       [9, 10]])
MATRIX 

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim # (Dimensiones = nº de "caminos" por los que se puede ir) 

2

In [11]:
MATRIX.shape # (Dos elementos donde cada uno contiene dos sub-elementos)

torch.Size([2, 2])

In [12]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3,7],
                        [4,5,6,7],
                        [7,8,9,7]],
                       
                       [[10,11,12,7],
                        [13,14,15,7],
                        [16,17,18,7]]])
TENSOR

tensor([[[ 1,  2,  3,  7],
         [ 4,  5,  6,  7],
         [ 7,  8,  9,  7]],

        [[10, 11, 12,  7],
         [13, 14, 15,  7],
         [16, 17, 18,  7]]])

In [13]:
TENSOR.ndim 

3

In [14]:
TENSOR.shape

torch.Size([2, 3, 4])

### Random tensors 

Why random tensors? 

NN start with random weights (random tensors) -> look at data -> update -> look data -> (...)

In [15]:
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.4839, 0.7987, 0.5119, 0.6049],
         [0.0308, 0.5944, 0.4052, 0.8905],
         [0.4375, 0.1705, 0.0639, 0.1402]]])

In [16]:
random_tensor.ndim # (Matriz)

3

In [17]:
random_tensor.shape # (3 filas, 4 columnas)

torch.Size([1, 3, 4])

In [18]:
# Create random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.ndim, random_image_size_tensor.shape

(3, torch.Size([224, 224, 3]))

In [19]:
random_image_size_tensor

tensor([[[5.1095e-01, 9.7253e-01, 1.6662e-01],
         [9.5364e-01, 8.6247e-01, 3.5689e-01],
         [6.2320e-01, 5.7783e-01, 6.4441e-01],
         ...,
         [3.2731e-01, 2.3088e-01, 1.7486e-02],
         [3.1804e-02, 8.5454e-01, 5.4096e-02],
         [8.2227e-01, 4.6879e-01, 3.9290e-01]],

        [[7.0304e-04, 7.3104e-01, 5.2357e-01],
         [1.0409e-02, 3.2124e-01, 6.1057e-01],
         [2.9702e-01, 5.5370e-01, 7.8685e-01],
         ...,
         [7.3054e-01, 1.2961e-01, 9.9554e-01],
         [2.2757e-01, 3.4823e-01, 4.2604e-02],
         [5.7891e-01, 2.1139e-01, 7.8240e-01]],

        [[1.1037e-01, 7.4539e-01, 7.9907e-01],
         [4.5550e-01, 5.9809e-01, 3.8981e-01],
         [9.8910e-01, 1.2288e-01, 9.2086e-01],
         ...,
         [8.1954e-01, 2.5988e-01, 2.2851e-01],
         [5.0477e-01, 1.3430e-01, 1.8047e-01],
         [9.8147e-01, 6.5147e-01, 9.5450e-01]],

        ...,

        [[9.4460e-01, 8.9026e-01, 7.1514e-01],
         [6.7985e-01, 2.3493e-01, 6.0330e-01]

In [20]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros * random_tensor # Element-wise multiplication

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [22]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like 

In [24]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Tensors like 
ten_zeros = torch.zeros_like(input=one_to_ten) 
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**NOTE**: Tensor datatypes are one of the big three issues with PyTorch & Deep learning:
    1. Tensors not right datatype
    2. Tensors not right shape 
    3. Tensors not right device 

In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What data type is the tensor (float32, float16,...)
                               device=None, # What device is the tensor on (CPU, GPU)
                               requires_grad=False) # Whetther or not to track gradients with this tensor

float_32_tensor.dtype

torch.float32

In [27]:
float_16_tensor = float_32_tensor.type(torch.float16) # Changes tensor datatype to another 

In [28]:
float_16_tensor * float_32_tensor # Works, but not all operations works

tensor([ 9., 36., 81.])

In [29]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [30]:
int_32_tensor * float_32_tensor # Works, but not all operations works

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype -> 'tensor.dtype'
2. Tensors not right shape -> 'tensor.shape'
3. Tensors not right device -> 'tensor.device'

In [31]:
# Create tensor 
some_tensor = torch.rand(size=(3, 4))
some_tensor

tensor([[0.4504, 0.7138, 0.3849, 0.1087],
        [0.3452, 0.6753, 0.0976, 0.2769],
        [0.3381, 0.6993, 0.7619, 0.1506]])

In [32]:
print(f"Some tensor: \n{some_tensor}")
print(f"- Datatype of tensor: {some_tensor.dtype}")
print(f"- Shape of tensor: {some_tensor.shape}")
print(f"- Device tensor is on: {some_tensor.device}")

Some tensor: 
tensor([[0.4504, 0.7138, 0.3849, 0.1087],
        [0.3452, 0.6753, 0.0976, 0.2769],
        [0.3381, 0.6993, 0.7619, 0.1506]])
- Datatype of tensor: torch.float32
- Shape of tensor: torch.Size([3, 4])
- Device tensor is on: cpu


### Manipulating tensors 

Tensors operations:
1. Addition
2. Subtraction 
3. Multiplication (elemento-wise)
4. Division 
5. Matrix multiplication 

In [33]:
# Create a tensor 
tensor = torch.tensor([1, 2, 3])
tensor 

tensor([1, 2, 3])

In [34]:
# Addition and subtraction
tensor + 50, tensor - 50

(tensor([51, 52, 53]), tensor([-49, -48, -47]))

In [35]:
# Multiplication tensor 
tensor * 10

tensor([10, 20, 30])

In [36]:
# Try out pytorch in-built functions (se pueden utilizar las anteriores directamente, mas entendibles)
torch.mul(tensor, 10), torch.add(tensor, 50), torch.sub(tensor, 50)

(tensor([10, 20, 30]), tensor([51, 52, 53]), tensor([-49, -48, -47]))

In [37]:
### Matrix multiplications: element-wise 
print(f"{tensor} * {tensor} = {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3]) = tensor([1, 4, 9])


In [40]:
### Matrix multiplications: dot product
## Option 1: @ operator 
print(f"{tensor} @ {tensor}.T = {tensor @ tensor.T}")

# Option 2: torch.matmul function 
print(f"{tensor} @ {tensor}.T = {torch.matmul(tensor, tensor.T)}")

# Option 3: by hand 
print(f"{tensor} @ {tensor}.T = {tensor[0]*tensor[0] + tensor[1]*tensor[1] + tensor[2]*tensor[2]}")

tensor([1, 2, 3]) @ tensor([1, 2, 3]).T = 14
tensor([1, 2, 3]) @ tensor([1, 2, 3]).T = 14
tensor([1, 2, 3]) @ tensor([1, 2, 3]).T = 14


In [41]:
# Time comparations 
# By hand 
import time 
start = time.time()

value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
end = time.time()
print(f"Value: {value}")
print(f"Time taken: {(end - start)*1000} milliseconds")

start = time.time()
value = torch.matmul(tensor, tensor)
end = time.time()
print(f"Value: {value}")
print(f"Time taken: {(end - start)*1000} milliseconds")

Value: 14
Time taken: 2.236604690551758 milliseconds
Value: 14
Time taken: 0.6434917449951172 milliseconds


In [42]:
# Now trying with a larger tensor 
tensor2 = torch.rand(size=(1000, 1000), dtype=torch.float32, device="cuda")

start = time.time()
value = torch.matmul(tensor2, tensor2)
end = time.time()
print(f"Time taken: {(end - start)*1000} milliseconds")

value = 0
for i in range(len(tensor2)):
    value += tensor2[i] * tensor2[i]
end = time.time()
print(f"Time taken: {(end - start)*1000} milliseconds")

Time taken: 1033.468246459961 milliseconds
Time taken: 1042.6099300384521 milliseconds


### One of most common errors in deep learning: shape errors

In matrix multiplication, two main rules: <br>
1. **Inner dimensions** must match : (3,2,1) @ (1,5,7) @ (7,2,5) ...<br>
2. The resulting matrix has the shape of the **outer dimensions**: (2,3) @ (3,7) -> (2,7)<br>


In [43]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])

print(f"Multiplication {torch.mm(tensor_A, tensor_B.T)}") # torch.matmult = toch.mm
print(f"Shapes: \nA: {tensor_A.shape}\nB.T: {tensor_A.T.shape}\n\nInners dimensions match!")
print(f"\nNew shape: {torch.mm(tensor_A, tensor_B.T).shape} -> New shape match with outter dimensions!")

Multiplication tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Shapes: 
A: torch.Size([3, 2])
B.T: torch.Size([2, 3])

Inners dimensions match!

New shape: torch.Size([3, 3]) -> New shape match with outter dimensions!


### Finding the min, max, mean, sum, etc (tensor aggregation)

In [44]:
# Create tensor 
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [45]:
# Find min 
print("Min: ",torch.min(x), x.min()) # Same output, one it's a function and the other a class method 

# Find max 
print("Max: ",torch.max(x), x.max()) # '' 

Min:  tensor(0) tensor(0)
Max:  tensor(90) tensor(90)


In [46]:
# Find average
print("Mean:", torch.mean(x)) ## Error: wrong data type .type

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [47]:
x.dtype # Ints do not work with mean, in CUDA mean operations are optimized for float data types

torch.int64

In [48]:
print("Mean:", torch.mean(x.type(torch.float32))) # Corrected data type 

Mean: tensor(45.)


In [49]:
# Find sum 
torch.sum(x), x.sum() # Same output, one it's a function and the other a class method

(tensor(450), tensor(450))

### Finding positional min and max 

In [50]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [51]:
x.argmin(), x.argmax() # -> Returns the index of the min/max value 

(tensor(0), tensor(9))

In [52]:
x.min() == x[x.argmin()] # Same 

tensor(True)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping: repshapes an input tensor to a defined shape.
* View: return a view of an input tensor of a certain shape but keep the same memory as the original tensor.
* Stacking: combine multiple tensors on top of each other (vstack) or side by side.
* Squeeze: removes all `1`dimensions from a tensor.
* Unsqueeze: adds a `1`dimensions from a tensor.
* Permute: Return a view of the input tensor with dimensions permuted (swapped) in a certain way.

In [53]:
# Let's create a tesnor 
x2 = torch.arange(1., 11.)
x, x.shape

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.Size([10]))

In [55]:
# Reshape: Add and extra dimension 
#x2_reshaped = x2.reshape(1,7) # Do not work
#x2_reshaped, x2_reshaped.shape

In [56]:
# Reshape: Add and extra dimension 
x2_reshaped = x2.reshape(1,10) # Do work, but actually don't change the data
x2_reshaped, x2_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [57]:
# Reshape: Add and extra dimension 
x2_reshaped = x2.reshape(10,1) # Do work: we basically transpose the tensor  
x2_reshaped, x2_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]),
 torch.Size([10, 1]))

In [58]:
# Reshape: Add and extra dimension 
x2_reshaped = x2.reshape(2,5) # Do work: 2 x 5 = 10, same number of elements as original tensor.  
x2_reshaped, x2_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [59]:
# Change de view: quite similar to reshape, but shares the same memory
z = x.view(1, 10)
z, z.shape

(tensor([[ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]]), torch.Size([1, 10]))

In [60]:
# Prove: changing the view changes the original tensor
z[:, 0] = 77
print("X:",x,"\nZ:" ,z)
print("It changed!")

X: tensor([77, 10, 20, 30, 40, 50, 60, 70, 80, 90]) 
Z: tensor([[77, 10, 20, 30, 40, 50, 60, 70, 80, 90]])
It changed!


In [61]:
# Rebember x2:
x2, x2.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [62]:
# Stack tensors on top of each other 
x_stacked = torch.stack([x2, x2, x2, x2], dim=0)
print("Stacked at first dimension(0)\n")

x_stacked, x_stacked.shape

Stacked at first dimension(0)



(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
         [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([4, 10]))

In [63]:
x_stacked2 = torch.stack([x2, x2, x2, x2], dim=1)
print("Stacked at second dimension(1)\n")

x_stacked2, x_stacked2.shape

Stacked at second dimension(1)



(tensor([[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]),
 torch.Size([10, 4]))

In [64]:
# Vstack
x_vstacked = torch.vstack([x2,x2,x2,x2])
print(x_vstacked,"\n", x_vstacked.shape)

# Hstack 
x_hstacked = torch.hstack([x2,x2,x2,x2])
print(x_hstacked,"\n", x_hstacked.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) 
 torch.Size([4, 10])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,
         5.,  6.,  7.,  8.,  9., 10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
         9., 10.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) 
 torch.Size([40])


In [65]:
tmp1 = torch.tensor([[1,2],
                     [3,4]]) # (2,2)

tmp2 = torch.tensor([[5,6],
                     [7,8]]) # (2,2)

tmp3 = torch.vstack((tmp1,tmp2))
tmp3, tmp3.shape

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 torch.Size([4, 2]))

In [66]:
tmp1 = torch.tensor([[1,2],
                     [3,4]]) # (2,2)

tmp2 = torch.tensor([[5,6],
                     [7,8]]) # (2,2)

tmp3 = torch.hstack((tmp1,tmp2))
tmp3, tmp3.shape

(tensor([[1, 2, 5, 6],
         [3, 4, 7, 8]]),
 torch.Size([2, 4]))

In [67]:
tmp1 = torch.tensor([[1,2],[3,4]]) # (2,2)
tmp2 = torch.tensor([[5,6],[7,8]]) # (2,2)
tmp3 = torch.stack((tmp1,tmp2,tmp2), dim=0) # (2,2,2)

tmp3, tmp3.shape


(tensor([[[1, 2],
          [3, 4]],
 
         [[5, 6],
          [7, 8]],
 
         [[5, 6],
          [7, 8]]]),
 torch.Size([3, 2, 2]))

In [ ]:
# Torch squeeze: it eliminates the extra dimensions that are 1
# Example: 
# Original tensor: 1 x 9
# After squeeze: 9
x_reshaped = torch.tensor([[5,2,3,4,5,6,7,8,9]], dtype=torch.float32) 
x_reshaped.shape, x_reshaped

(torch.Size([1, 9]), tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [79]:
x_reshaped_squeezed = x_reshaped.squeeze() 
x_reshaped_squeezed, x_reshaped_squeezed.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [85]:
x_reshaped3 =  torch.tensor([[[5,2,3,4,5,6,7,8,9]]], dtype=torch.float32) 
print(f"Tensor with extra '1' dimensions: {x_reshaped3.shape}\nAfter squeeze: {x_reshaped3.squeeze().shape}") 

Tensor with extra '1' dimensions: torch.Size([1, 1, 9])
After squeeze: torch.Size([9])


In [92]:
# Torch unsqueeze: adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor {x_reshaped_squeezed.shape}")
print(f"After unsqueeze at dim 0 {x_reshaped_squeezed.unsqueeze(dim=0).shape}")
print(f"After unsqueeze at dim 1 {x_reshaped_squeezed.unsqueeze(dim=1).shape}")

Previous tensor torch.Size([9])
After unsqueeze at dim 0 torch.Size([1, 9])
After unsqueeze at dim 1 torch.Size([9, 1])


In [ ]:
# Torch permute: rearranges the dimensions of a target tensor in a specific order
## Gives a view, so it shares the same memory, it's nota copy.

x_original = torch.rand(size=(224,224,3)) # (Height Width Channels)
x_original.shape

# Permute the original tensor to rearrange the dimensions 
x_permuted = x_original.permute(2, 0, 1) 

# Changes: 
# Original(2) -> Permuted(0)
# Original(0) -> Permuted(1)
# Original(1) -> Permuted(2)

print(f"Original tensor: {x_original.shape}")
print(f"Permuted tensor: {x_permuted.shape}")

Original tensor: torch.Size([224, 224, 3])
Permuted tensor: torch.Size([3, 224, 224])


### Indexing with pytorch (selection data from tensors)
Quite similar to NumPy 

In [100]:
# Create a tensor 
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [109]:
# Let's index 
print(f"Indexing first dimension: \n{x[0]}")
print(f"Indexion second dimension: \n{x[0,0]}")
print(f"Indexing third dimension: \n{x[0,0,0]}")

# By the way, x[i][j][k] equals x[i,j,k]
# To select all elements in a dimension use ":"

x[0, :, 2]

Indexing first dimension: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Indexion second dimension: 
tensor([1, 2, 3])
Indexing third dimension: 
1


tensor([3, 6, 9])

## PyTorch and NumPy 

Because NumPy popularity, PyTorch can interact with certain functions with NumPy 

* Data in numpy, want in pytorch: `torch.from_numpy(ndarray)`
* pytorch tensor -> numpy: `torch.tensor.numpy()`

In [ ]:
# NumPy to PyTorch 
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array,"\n",tensor) # dtype is float64 cause it is numpy default data type
# However, torch default data type is float32, so be careful -> WRONG DATA TYPE ERROR INCOMING!

[1. 2. 3. 4. 5. 6. 7.] 
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [ ]:
# Change array value
array = array + 1
array, tensor

# from_numpy make a copy, not shared memory 

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# PyTorch to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor
# Same for dtype, numpy takes the same dtype as the tensor 

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [115]:
tensor = tensor + 1
tensor, numpy_tensor

# Do not share memory too

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproductbility

Idea: **Random seed**

In [119]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A,"\n",random_tensor_B,"\n")
print(random_tensor_A == random_tensor_B)

tensor([[0.5531, 0.6672, 0.0865, 0.8787],
        [0.4760, 0.3554, 0.5411, 0.9239],
        [0.3883, 0.7602, 0.6547, 0.0512]]) 
 tensor([[0.7901, 0.6230, 0.2371, 0.5763],
        [0.7830, 0.0757, 0.9348, 0.7909],
        [0.0536, 0.8079, 0.9645, 0.1864]]) 

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let`s make it reproducible 
RANDOM_SEED = 123

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)
print(random_tensor_C == random_tensor_D)

# Torch.manual_seed works just once, so if you want to reset the seed, you have to call it again

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and python objects on GPU 

In [ ]:
## Check for GPU access wtih PyTorch
torch.cuda.is_available() # Boolean

True

In [124]:
# Setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device 

'cuda'

In [ ]:
# Number of devices 
torch.cuda.device_count() #  In my case of course is 1 GPU

1

In [127]:
# Putting tensors and models on the GPU
tensor = torch.tensor([1,2,3], device = "cpu")
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU is available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu # With multiple GPUs you will need the cuda:index

tensor([835632, 0, 3422636128], device='cuda:0')

In [129]:
# Moving tensors back to the cpu   
tensor_back_cpu = tensor_on_gpu.cpu() # Back to cpu
numpy_array =  tensor_back_cpu.numpy() # Into numpy 
