# **00 Fundamentals:** Exercises & Extra-curriculum 

In [2]:
# Libraries

import torch

#### **1.** Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with th documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on torch.Tensor and for torch.cuda.

#### **2.** Create a random tensor with shape (7, 7).


In [5]:
# Random tensor 
random_tensor = torch.rand(size=(7, 7))
random_tensor, random_tensor.shape

(tensor([[0.3549, 0.1576, 0.2762, 0.4055, 0.7844, 0.2963, 0.4810],
         [0.1068, 0.3481, 0.5156, 0.6210, 0.8228, 0.0690, 0.7382],
         [0.0527, 0.2450, 0.8501, 0.9824, 0.4383, 0.9065, 0.4980],
         [0.2023, 0.2736, 0.6979, 0.7073, 0.7607, 0.3450, 0.0437],
         [0.8088, 0.8362, 0.8323, 0.6883, 0.2380, 0.0439, 0.4216],
         [0.2157, 0.3789, 0.2249, 0.1352, 0.8795, 0.0551, 0.7357],
         [0.3639, 0.2939, 0.2709, 0.2464, 0.6935, 0.4086, 0.4374]]),
 torch.Size([7, 7]))

#### **3.** Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [9]:
# Creating another tensor 
random_tensor_2 = torch.rand(size=(1, 7))
random_tensor_2, random_tensor_2.shape

(tensor([[0.8885, 0.6213, 0.6986, 0.8082, 0.0563, 0.2940, 0.7607]]),
 torch.Size([1, 7]))

In [ ]:
# Shapes
print(f"Size of tensor_1: {random_tensor.shape}\nSize of tensor_2: {random_tensor_2.shape}")

Size of tensor_1: torch.Size([7, 7])
Size of tensor_2: torch.Size([1, 7])


In [11]:
# Matrix multiplication
# Because inner dimensions must match, we must transpose the second one
tensor_result = torch.matmul(random_tensor, random_tensor_2.T)
tensor_result, tensor_result.shape


(tensor([[1.4311],
         [1.8014],
         [2.2569],
         [1.5864],
         [2.7229],
         [1.3188],
         [1.3861]]),
 torch.Size([7, 1]))

In [14]:
print(f"As expected, the shape of the result tensor is the outer dimensions of the other two.")
print(f"Tensor 1: {random_tensor.shape}, Tensor 2 (transposed): {random_tensor_2.T.shape} => Result: {tensor_result.shape}")

As expected, the shape of the result tensor is the outer dimensions of the other two.
Tensor 1: torch.Size([7, 7]), Tensor 2 (transposed): torch.Size([7, 1]) => Result: torch.Size([7, 1])


#### **4.** Set the random seed to 0 and do exercises 2 & 3 over again.

In [49]:
# Random tensors
manual_seed = 0
torch.manual_seed(manual_seed)
t1 = torch.rand(size=(7,7))

manual_seed = 123
torch.manual_seed(manual_seed)
t2 = torch.rand(size=(1,7))

# Multiplication 
t_result = t1 @ t2.T
t_result, t_result.shape


(tensor([[1.2961],
         [0.9723],
         [1.4309],
         [1.8563],
         [1.2337],
         [1.3930],
         [1.1776]]),
 torch.Size([7, 1]))

#### **5.** Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [ ]:
if torch.cuda.is_available():
    torch.cuda.manual_seed

In [ ]:
torch.manual_seed(1)
torch.rand(size=(2,2), device="cuda") # This works for GPU too, but there are specific function to GPU

tensor([[0.8903, 0.0275],
        [0.9031, 0.5386]], device='cuda:0')

In [28]:
# Set seed just for gpu
torch.cuda.manual_seed(1234)
t3 = torch.rand(size=(2,2), device="cuda")
t3

tensor([[0.1272, 0.8167],
        [0.5440, 0.6601]], device='cuda:0')

#### **6.** Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). 

In [46]:
torch.manual_seed(1234)
t1 = torch.rand(size=(2,3), device="cuda")
torch.manual_seed(1234)
t2 = torch.rand(size=(2,3), device="cuda")
t1, t2

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'))

#### **7.** Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [54]:
t3 = torch.mm(t1, t2.T)
# Equivalent: t1 @ t2.T 
t3

tensor([[1.2961],
        [0.9723],
        [1.4309],
        [1.8563],
        [1.2337],
        [1.3930],
        [1.1776]])

#### **8.** Find the maximum and minimum values of the output of 7.

In [55]:
t3.max(), t3.min()

(tensor(1.8563), tensor(0.9723))

#### **9.** Find the maximum and minimum index values of the output of 7.

In [56]:
t3.argmax(), t3.argmin()

(tensor(3), tensor(1))

#### **10.** Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.


In [62]:
# Random tesnor shape (1,1,1,10)
torch.manual_seed(7)
t1 = torch.rand(size=(1,1,1,10))
torch.manual_seed(7)
t2 = torch.rand(10)

print(f"First tensor: \n{t1}\nWith shape: {t1.shape}")
print(f"Second tensor: \n{t2}\nWith shape: {t2.shape}")

First tensor: 
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
With shape: torch.Size([1, 1, 1, 10])
Second tensor: 
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
With shape: torch.Size([10])
